export const FETHC_FILMS_START = 'FETHC_FILMS_START';
export const FETHC_FILMS_SUCCESS = 'FETHC_FILMS_SUCCESS';
export const FETHC_FILMS_ERROR = 'FETHC_FILMS_ERROR';


export const SWITCH_FILM_OVERVIEW = 'SWITCH_FILM_OVERVIEW';
export const GET_FILM_VIDEO = 'GET_FILM_VIDEO';